# docker-compose.yml
version: "3.8"
services:
  web:
    # image: erich2s/maintenance-management-system:latest
    build: .
    environment:
      # web-push 设置
      WEB_PUSH_CONTACT: ${WEB_PUSH_CONTACT}
      NEXT_PUBLIC_VAPID_KEY: ${NEXT_PUBLIC_VAPID_KEY}
      PRIVATE_VAPID_KEY: ${PRIVATE_VAPID_KEY}
      # JWT secret
      SECRET: ${SECRET}
      # DB
      DATABASE_URL: postgres://admin:123456@postgres:5432/nextjs
      # ！！生产环境中这里要手动设置NEXTAUTH_URL成宿主机的地址
      NEXTAUTH_URL: http://localhost
    restart: always
    container_name: nextjs_container
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx_container
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    expose:
      - 80
  postgres:
    image: postgres:15.4
    restart: always
    container_name: postgres_container
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
