# docker-compose.yml
version: "3.8"
networks:
  app-network:
    driver: bridge
services:
  web:
    build:
      context: .
      args:
        # 需要在构建镜像时传入NEXT_PUBLIC_VAPID_KEY，因为他是在构建前端静态文件时被需要的
        NEXT_PUBLIC_VAPID_KEY: BDeQByhHcxy084_JFou3rHlqiSpFvPZhUWjQKb1QlU6TjXL8mJd3usKDsQDzEeZ1HJOuultQgtPRlGOqgrrLnQA
    environment:
      # web-push 设置
      - WEB_PUSH_CONTACT=mailto:erich2s@qq.com
      # - NEXT_PUBLIC_VAPID_KEY=BDeQByhHcxy084_JFou3rHlqiSpFvPZhUWjQKb1QlU6TjXL8mJd3usKDsQDzEeZ1HJOuultQgtPRlGOqgrrLnQA
      - PRIVATE_VAPID_KEY=rZpj98WVatLMqzgWkC_mQgAbzG3WAZAtiw9hiMW3taY
      # JWT secret
      - SECRET=mysecret123
      # DB
      - DATABASE_URL=postgresql://admin:123456@postgres:5432/maintenance_sys?schema=public
      # ！！生产环境中这里要手动设置NEXTAUTH_URL成宿主机的地址
      - NEXTAUTH_URL=http://localhost
    restart: always
    container_name: nextjs_container
    # 注释掉ports，因为nginx会代理到80端口，只通过nginx暴露80端口让外部访问不到3000端口
    # ports:
    #   - 3000:3000
    depends_on:
      - postgres
    #环境变量不要加双引号
    networks:
      - app-network
  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx_container
    ports:
      - 80:80
    depends_on:
      - postgres
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
  postgres:
    image: postgres:15.4
    restart: always
    container_name: postgres_container
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    volumes:
      - postgres:/var/lib/postgresql/data
    # ports:
    #   - 5432:5432
    networks:
      - app-network

volumes:
  postgres:
