# docker-compose.yml
version: "3.8"
services:
  web:
    build:
      context: .
      args:
        # 需要在构建镜像时传入NEXT_PUBLIC_VAPID_KEY，因为他是在构建前端静态文件时被需要的
        NEXT_PUBLIC_VAPID_KEY: ${NEXT_PUBLIC_VAPID_KEY}
    #环境变量不要加双引号
    environment:
      # web-push 设置
      WEB_PUSH_CONTACT: ${WEB_PUSH_CONTACT}
      # 在这同时也要写
      NEXT_PUBLIC_VAPID_KEY: ${NEXT_PUBLIC_VAPID_KEY}
      PRIVATE_VAPID_KEY: ${PRIVATE_VAPID_KEY}
      # JWT secret
      SECRET: ${SECRET}
      # DB
      DATABASE_URL: postgres://admin:123456@postgres:5432/nextjs
      # ！！生产环境中这里要手动设置NEXTAUTH_URL成宿主机的地址
      NEXTAUTH_URL: http://localhost
    restart: always
    container_name: nextjs_container
    # 注释掉ports，因为nginx会代理到80端口，只通过nginx暴露80端口让外部访问不到3000端口
    # ports:
    #   - 3000:3000
    depends_on:
      - postgres
  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx_container
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  postgres:
    image: postgres:15.4
    restart: always
    container_name: postgres_container
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    volumes:
      - postgres:/var/lib/postgresql/data
    # ports:
    #   - 5432:5432

volumes:
  postgres:
